steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/mlop-cg-data-and-insights/prediction-container:latest', '.']
  env: ["AIP_STORAGE_URI=gs://mlops-vertex-capgemini/artifacts",
        "PROJECT_ID=mlop-cg-data-and-insights",
        "LOGGER_PUBSUB_TOPIC=logger-pubsub-topic"]
images:
- 'gcr.io/mlop-cg-data-and-insights/prediction-container:latest'

options:
  machineType: "E2_HIGHCPU_8"